In [172]:
a = int(input("Enter a value : "))
b = int(input("Enter b value : "))
print("add : ",a+b)
print("Div : ",a/b)
print("Sub : ",a-b)
print("Mul : ",a*b)

Enter a value : 10
Enter b value : 0
add :  10


ZeroDivisionError: division by zero

In [2]:
try:
    a = int(input("Enter a value : "))
    b = int(input("Enter b value : "))
    print("add : ",a+b)
    print("Div : ",a/b)
except ValueError:
    print("Invalid Input")
except ZeroDivisionError:
    print("Divide with zero not possible")    
print("Sub : ",a-b)
print("Mul : ",a*b)

Enter a value : 15
Enter b value : 2
add :  17
Div :  7.5
Sub :  13
Mul :  30


In [66]:
# Handling an exception
try:
    a = int(input("Enter a value : "))
    b = int(input("Enter b value : "))
    print("add : ",a+b)
    printresult = a/b
except ValueError:
    print("Enter only integers")
except ZeroDivisionError:
    print("Cannot divide by zero.")
print("Sub : ",a-b)
print("Mul : ",a*b)
print("Exception Handling")

Enter a value : 5
Enter b value : 0
add :  5
Cannot divide by zero.
Sub :  5
Mul :  0
Exception Handling


### try with else Clause

In [10]:
# Handling an exception
try:
    a = int(input("Enter a value : "))
    b = int(input("Enter b value : "))
    print("add : ",a+b)
    result = a/b
except (ValueError,NameError):
    print("Enter only integers / trying to use undefined variable")
except ZeroDivisionError:
    print("Cannot divide by zero.")
else:
    print("Division : ",result)
print("Sub : ",a-b)
print("Mul : ",a*b)

Enter a value : 10
Enter b value : f
Enter only integers / trying to use undefined variable
Sub :  10
Mul :  0


In [18]:
x = [5,8,9,13]

def replace(x,i,e):
    try:
        x[i] = e
    except IndexError:
        print("Index not available")
    else:
        print("After replacement : ",x)

#find(list_variable,index,element to be replaced) 
replace(x,2,21)
replace(x,8,21)
replace(x,1,100)

After replacement :  [5, 8, 21, 13]
Index not available
After replacement :  [5, 100, 21, 13]


## finally Keyword

In [86]:
# Handling an exception
try:
    a = int(input("Enter a value : "))
    b = int(input("Enter b value : "))
    print("add : ",a+b)
    result = a/b
except ValueError:
    print("Enter only integers")
except ZeroDivisionError:
    print("Cannot divide by zero.")
else:
    print("Division : ",a/b)
finally:
    print("Sub : ",a-b)
    print("Mul : ",a*b)

Enter a value : 10
Enter b value : 0
add :  10
Cannot divide by zero.
Sub :  10
Mul :  0


In [57]:
import builtins
print(dir(builtins))


['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError

## Raising Exceptions

### Without Raising an Error

Python Program which creates a phone directory, with name and contact number. 

Before adding to the directory, it check whether the phone number if valid add to directory, otherwise creates an empty directory

In [15]:
def valid_pn1(n):  #valid phone number will exactly have 10 digits
    c = 0
    while n!=0:
        c += 1
        n //= 10
    if c != 10:
        return False
    else:
        return True

In [20]:
name = input("Enter Your name : ")    
phone_no = int(input("Enter Your number: "))
directory = {}
if valid_pn1(phone_no): # by passing the phone number to valid_pn() function it checks whether it is valid or not
    directory[name] = phone_no
print(directory)

Enter Your name : vishnu
Enter Your number: 9874563210
{'vishnu': 9874563210}


### Same as Above - But It raise the Error

Python Program which creates a phone directory, with name and contact number. 

Before adding to the directory, it check whether the phone number is valid or not, will be added to the directory once it is valid

In [161]:
def valid_pn(n):  #valid phone number will exactly have 10 digits
    c = 0
    while n!=0:
        c += 1
        n //= 10
    if c != 10:
        raise ValueError("Invalid Phone Number")
    else:
        return True            

In [163]:
name = input("Enter Your name : ")    
phone_no = int(input("Enter Your number: "))
directory = {}

if valid_pn(phone_no): # by passing the phone number to valid_pn() function it checks whether it is valid or not
    directory[name] = phone_no
print(directory)

Enter Your name : vishnu
Enter Your number: 98745632


ValueError: Invalid Phone Number

### Now will handle the raised exception

By including the code in Try and Except Block

In [166]:
def valid_pn(n):  #valid phone number will exactly have 10 digits
    c = 0
    while n!=0:
        c += 1
        n //= 10
    try:
        if c != 10:
            raise ValueError
        else:
            return True 
    except ValueError:
        print ("Invalid Phone Number from except")

In [167]:
name = input("Enter Your name : ")    
phone_no = int(input("Enter Your number: "))
directory = {}

if valid_pn(phone_no): # by passing the phone number to valid_pn() function it checks whether it is valid or not
    directory[name] = phone_no

print(directory)

Enter Your name : vishnu
Enter Your number: 987456
Invalid Phone Number from except
{}


### Creating user defined exception

In the above code we have used built in Exception (ValueError)

But now will try to create our own exception

In [168]:
class InvalidPhoneNumber(Exception): #creates a new exception class - InvalidPhoneNumber
    pass

In [169]:
def valid_pn(n):  #valid phone number will exactly have 10 digits
    c = 0
    while n!=0:
        c += 1
        n //= 10
    try:
        if c != 10:
            raise InvalidPhoneNumber  
        else:
            return True 
    except InvalidPhoneNumber:
        print ("Invalid Phone Number")

In [170]:
name = input("Enter Your name : ")    
phone_no = int(input("Enter Your number: "))
directory = {}
name.isalpha()
if valid_pn(phone_no): # by passing the phone number to valid_pn() function it checks whether it is valid or not
     directory[name] = phone_no
        
print(directory)

Enter Your name : vishnu
Enter Your number: 9874563210
{'vishnu': 9874563210}


## Another Example

#### WITHOUT AGE VALIDATION
Get the name, age, mark from the user and generate the dictonary as below

**Sample Output**
{'NAME': 'Vishnu', 'AGE': 30, 'MARKS': [89, 86, 85, 84, 87, 88], 'TOTAL': 519, 'AVERAGE': 86.5}

In [155]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
marks = []
total = 0
print("Enter 6 subject marks: ")
for i in range(6):
    marks.append(int(input()))
for i in marks:
    total += i
avg = round(total/6,3)
detail = {}
detail["NAME"] = name
detail["AGE"] = age
detail["MARKS"] = marks
detail["TOTAL"] = total
detail["AVERAGE"] = avg
print(detail)

Enter your name: Vishnu
Enter your age: 30
Enter 6 subject marks: 
89
86
85
84
87
88
{'NAME': 'Vishnu', 'AGE': 30, 'MARKS': [89, 86, 85, 84, 87, 88], 'TOTAL': 519, 'AVERAGE': 86.5}


#### WITH AGE VALIDATION - Just raise an error if Age is Negative Value

Get the name, age, mark from the user and generate the dictonary as below. If the age is Negative value then it should raise an Error

**Sample Output**
{'NAME': 'Vishnu', 'AGE': 30, 'MARKS': [89, 86, 85, 84, 87, 88], 'TOTAL': 519, 'AVERAGE': 86.5}

In [48]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
marks = []
total = 0
print("Enter 6 subject marks: ")
for i in range(6):
    marks.append(int(input()))
for i in marks:
    total += i
avg = round(total/6,3)
detail = {}
detail["NAME"] = name
if age <= 0:
    raise Exception("Invalid Input for Age- Negative or Zero")
else:
    detail["AGE"] = age
detail["MARKS"] = marks
detail["TOTAL"] = total
detail["AVERAGE"] = avg
print(detail)

Enter your name: sdf
Enter your age: -9
Enter 6 subject marks: 
56
56
23
56
56
56


Exception: Invalid Input for Age- Negative or Zero

## Handling raised exception

#### WITH AGE VALIDATION - Handles the raised error if Age is Negative Value

Get the name, age, mark from the user and generate the dictonary as below. If the age is Negative value then it should raise an Error

**Sample Output**
{'NAME': 'Vishnu', 'AGE': 30, 'MARKS': [89, 86, 85, 84, 87, 88], 'TOTAL': 519, 'AVERAGE': 86.5}

In [45]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
marks = []
total = 0
print("Enter 6 subject marks: ")
for i in range(6):
    marks.append(int(input()))
for i in marks:
    total += i
avg = round(total/6,3)
detail = {}
try:
    if age <= 0:
        raise ValueError
except ValueError:
    print("Invalid Input for Age- Negative or Zero")
else
    detail["NAME"] = name
    detail["AGE"] = age
    detail["MARKS"] = marks
    detail["TOTAL"] = total
    detail["AVERAGE"] = avg
print(detail)

IndentationError: expected an indented block (Temp/ipykernel_19464/2229584251.py, line 16)

In [53]:
class User_Exception(Exception):
    pass

age = int(input("Enter ur age: "))
try:
    if age < 0 or age < 18:
        raise User_Exception
except User_Exception:
    print("Not Eligible to Vote")
else:
        print("Eligible to Vote")

Enter ur age: 28
Eligible to Vote


In [61]:
class GradeValueError(Exception):
    pass

def calculate_average_grade(grades):
    total = 0
    count = 0
    for grade in grades:
        if grade < 0 or grade > 100:
            raise GradeValueError
        total += grade
        count += 1
    return round(total / count, 2)

In [64]:
calculate_average_grade([98, 87, 70])
calculate_average_grade([98, 87, 170])

GradeValueError: 

In [8]:
n = int(input("Enter number of elements in a list: "))
l = []
for i in range(n):
    l.append(int(input()))
try:
    ind = int(input("Enter the index value: "))
    print(l[ind])
except IndexError:
    print("Index is not present, the last index value is ",n-1)

Enter number of elements in a list: 6
12
45
18
19
15
22
Enter the index value: 7
Index is not present, the last index value is  5
